version: "3"
services:
  codeigniter:
    build: 
      context: 'codeigniter/${BACK_END}'
      dockerfile: 'Dockerfile-${PHP_VERSION}'
      args:
          - 'BACK_END=${BACK_END}'
          - 'USER_ID=${USER_ID}'
          - 'GROUP_ID=${GROUP_ID}'
          - 'PHP_VERSION=${PHP_VERSION}'
          - 'XDEBUG=${XDEBUG}'
          - 'INSTALL_ADDITIONAL_EXTENSIONS=${INSTALL_ADDITIONAL_EXTENSIONS}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CODEIGNITER}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${CODE_PORT}:80'
  mysql:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - 'MARIADB_DATABASE=${DB_NAME}'
      - 'MARIADB_USER=${DB_USER}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
    ports:
      - '${MYSQL_PORT}:3306'
volumes: {}