version: "3"
services:
  codeigniter:
    image: deckapp/codeigniter:latest
    ports:
      - '${CODE_PORT}:80'
    links:
      - 'mysql'
    volumes:
      - '${APP_CODE_PATH_HOST}:/var/www/html'
  mysql:
    build:
      context: ./mysql
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}/mysql:/app'
      - '${MYSQL_PATH}/my.cnf:/etc/mysql/my.cnf'
    ports:
      - '${MYSQL_PORT}:3306'

