version: "3"
services:
  codeigniter:
    build: 
      context: ./codeigniter
    ports:
      - "${CODE_PORT}:80"
    links:
      - "mysql"
    volumes:
      - "${APP_CODE_PATH_HOST}:/var/www/html"
  mysql:
    build:
      context: "./mysql"
      args:
        - "MYSQL_VERSION=${MYSQL_VERSION}"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "TZ=${WORKSPACE_TIMEZONE}"
    volumes:
      - "${DATA_PATH_HOST}/mysql:/var/lib/mysql"
      - "${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d"
    ports:
      - "${MYSQL_PORT}:3306"
volumes:
  codeigniter:
    driver: "${VOLUMES_DRIVER}"
  mysql:
    driver: "${VOLUMES_DRIVER}"
